Typo in example JS
Example is not valid syntax and resulted in 
> SyntaxError: missing } after property list
due to missing `,` after `country: "United States"`